name: Test xllify-build action

on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:

jobs:
  exercise-action:
    name: Exercise action
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: xllify
        id: xllify
        uses: ./
        with:
          xll_filename: bs
          xllify_version: 0.9.3
          embed_scripts: |
            black_scholes.luau
            hello.luau
          xllify_key: earlyadopter

      - name: Upload XLL artifact
        uses: actions/upload-artifact@v4
        with:
          name: bs
          path: ${{ steps.xllify.outputs.xll_path }}
