name: Test xllify-build action

on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:

jobs:
  exercise-action:
    name: Exercise action
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: xllify
        id: xllify
        uses: ./
        with:
          xll_filename: hello
          xllify_version: 0.3.47
          luau_scripts: |
            hello.luau
            the_answer.luau
            black_scholes.luau
          xllify_key: not-needed

      - name: Upload XLL artifact
        uses: actions/upload-artifact@v4
        with:
          name: hello
          path: ${{ steps.xllify.outputs.xll_path }}

      - name: Upload test-results artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: ${{ steps.xllify.outputs.test_results_path }}
